// timeline_record.h : Layout snapshot data structures for Desktop Timeline
#pragma once
#include <Windows.h>
#include <vector>
#include <string>

// A single icon position in a layout snapshot
struct TimelineIcon {
    std::wstring name;       // Display name (e.g., "This PC", "Recycle Bin")
    std::wstring path;       // Full path for cross-device matching
    int x, y;                // Pixel position
    int gridRow, gridCol;    // Grid coordinates (for smart placement)
};

// A complete layout snapshot
struct TimelineSnapshot {
    std::wstring id;         // Unique ID: "20260629_153000_auto"
    std::wstring name;       // "[Auto] 2026-06-29 15:30" or user-assigned
    std::wstring timestamp;  // ISO format: "2026-06-29T15:30:00"
    int iconCount;
    int monitorWidth;
    int monitorHeight;
    int dpi;
    std::vector<TimelineIcon> icons;
    bool isCheckpoint;
    bool isAutoGenerated;

    // Multi-monitor support
    int monitorCount;
    RECT monitors[8];  // Monitor layout at capture time
};

// Lightweight summary for list display
struct TimelineSummary {
    std::wstring id;
    std::wstring name;
    std::wstring timestamp;
    int iconCount;
    int changedCount;        // -1 if unknown
    bool isCheckpoint;
    bool isAutoGenerated;
};
